// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/Navbar/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} h-screen min-h-fit`}>
          <div className=''>
            <Navbar />
          </div>
          <div className='h-[calc(100vh-4rem)]'>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
